language: objective-c
osx_image: xcode7
before_install:
- gem install cocoapods --no-document
- gem install xcpretty --no-document
script:
- set -o pipefail
- xcodebuild -workspace Xcode/HttpBasicAuth.xcworkspace -scheme HttpBasicAuth test -sdk macosx | xcpretty -c
- pod lib lint
